name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - run: deno lint
    - run: deno test --allow-read=testcases
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v3
    - name: Push to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: "."
        exclude_assets: ".github,testcases,.*,*.md,*.test.mjs"
